name: Testing build on macos-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up requirements & configuration variables
        run: |
          brew update
          brew install cmake
          pip install --upgrade pip wheel build
          pip install -r test_requirements.txt

      - name: make
        shell: bash
        run: |
          python -m build

      - name: install
        shell: bash
        run: |
          pip install dist/*.whl

      - name: make test
        shell: bash
        run: |
          export CASM_PREFIX=$(python -m libcasm.casmglobal --prefix)
          python -m pytest -rsap python/tests

      - name: upload libcasm-clexulator-macos-latest-x86_64-dist
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: libcasm-mapping-macos-latest-x86_64-dist
          path: dist
